DROP DATABASE IF EXISTS shopping_db;

CREATE DATABASE shopping_db;

USE shopping_db;

CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  hashPassword VARCHAR(255) NOT NULL,
  phone_mobile VARCHAR(15) NOT NULL,
  address VARCHAR(150) NOT NULL,
  isMember BOOLEAN DEFAULT 0,
  isAdmin BOOLEAN DEFAULT 0 
);

CREATE TABLE category (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(150) NOT NULL 
);

CREATE TABLE sous_category (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(150) NOT NULL,
  category_id INT,
  FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);

CREATE TABLE product (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  stock INT,
  img_url VARCHAR(250),
  sous_category_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (sous_category_id) REFERENCES sous_category(id) ON DELETE CASCADE
);

CREATE TABLE avis (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  comment VARCHAR(255) NOT NULL,
  note INT,
  product_id INT,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

CREATE TABLE wishlist (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  quantity INT NOT NULL,
  product_id INT,
  user_id INT,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE newsletter (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE cart (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE product_cart (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  quantity INT NOT NULL,
  product_id INT,
  cart_id INT,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE
);

CREATE TABLE payment (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  total_price DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE command (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  payment VARCHAR(255) NOT NULL,
  statut VARCHAR(255) NOT NULL,
  user_id INT,
  cart_id INT,
  payment_id INT,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
  FOREIGN KEY (payment_id) REFERENCES payment(id) ON DELETE CASCADE
);

CREATE TABLE detail_order (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  quantity INT NOT NULL,
  product_id INT,
  command_id INT,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  FOREIGN KEY (command_id) REFERENCES command(id) ON DELETE CASCADE
);
